## TYPE ROUTER
## UDP client template for router-based deployments

client
dev tun
proto udp

ca ca.crt
cert __CLIENT__.crt
key __CLIENT__.key
remote-cert-tls server
tls-auth ta.key 1
key-direction 1
explicit-exit-notify 1

remote __VPN_HOST__ __VPN_PORT__
nobind
persist-tun
persist-key
auth-nocache

tls-version-min 1.2
data-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305
data-ciphers-fallback AES-128-GCM
auth SHA256

tun-mtu 1500
mssfix 1450

verb 3
