## Run OpenVPN with reduced privileges ##
user openvpn
group openvpn

## Listen on IPv4 / UDP / standard OpenVPN port ##
proto udp
port __VPN_PORT__
dev tun0

## Basic hardening / stability ##
persist-key
persist-tun
topology subnet
keepalive 10 60
explicit-exit-notify 1

## Packet authentication ##
auth SHA256

## VPN subnet + persistent client IP mapping ##
server 10.10.1.0 255.255.255.0
ifconfig-pool-persist /etc/openvpn/client-ips-default.txt

## PKI / certificates ##
ca   /etc/openvpn/server/ca.crt
cert /etc/openvpn/server/server.crt
key  /etc/openvpn/server/server.key
dh /etc/openvpn/server/dh4096.pem

## TLS protection ##
tls-auth /etc/openvpn/server/ta.key 0

## Minimum TLS version ##
tls-version-min 1.2

## Data channel ciphers ##
data-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305
data-ciphers-fallback AES-128-GCM

## DNS for VPN clients ##
push "dhcp-option DNS 10.10.1.1"

## Client-to-client communication ##
client-to-client

## MTU / MSS tuning ##
tun-mtu 1500
mssfix 1450

## Socket buffers ##
sndbuf 0
rcvbuf 0

## Queue length ##
txqueuelen 1000

## Certificate revocation list ##
#crl-verify /etc/openvpn/server/crl.pem

## Logging ##
verb 3
status /etc/openvpn/openvpn-status.log
log-append /var/log/openvpn/server.log
